# Generated by Django 5.0.6 on 2024-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='pricee',
            new_name='price',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
