# Generated by Django 5.0.6 on 2024-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_desctiption_bookmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(db_column='desctiption'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.DecimalField(db_column='pricee', decimal_places=2, max_digits=6),
        ),
    ]
