# Generated by Django 5.0.6 on 2024-07-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_bookmodel_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
